CUSTOMER LOYALITY PREDICTION

DATA SET

In [ ]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

data1=pd.read_csv('Churn.csv')
data1

In [ ]:
import hashlib
import random
import string
d1 = data1[['CreditScore','Gender','Age','Tenure']].dropna()
display(d1.head())

In [ ]:
data1

In [ ]:
from tqdm.auto import tqdm
import seaborn as sns
import matplotlib.pyplot as plt

# Selecting a few columns for distribution plots
for column in tqdm(['Age', 'Tenure', 'Balance', 'EstimatedSalary'], desc='Plotting distributions'):
    plt.figure(figsize=(10, 4))
    sns.histplot(data1[column], kde=True)
    plt.title('Distribution of ' + column)
    plt.xlabel(column)
    plt.ylabel('Frequency')
    plt.show()


Search and Display NULL Values

In [ ]:
data1.apply(lambda x: sum(x.isnull()),axis=0)

DATA PREPROCESSING

In [ ]:
data1['Gender'].replace(['Female','Male'],[hash('female'),hash('male')],inplace=True)

In [ ]:
data1

In [ ]:
data1=data1.drop(['RowNumber','CustomerId','Surname','Geography'], axis=1)

In [ ]:
data1['balancehash']=data1['Balance'].apply(hash)

data1['estimatedhash']=data1['EstimatedSalary'].apply(hash)

data1['agehash']=data1['Age'].apply(hash)

data1['exihash']=data1['Exited'].apply(hash)

In [ ]:
data1

Covariance and Correlation

In [ ]:
data1.cov()

In [ ]:
data1.corr()

In [ ]:
data1

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the correlation matrix
corr_matrix = data1.corr()

# Generate a mask for the upper triangle
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(11, 9))

# Generate a custom diverging colormap
cmap = sns.diverging_palette(230, 20, as_cmap=True)

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr_matrix, mask=mask, cmap=cmap, vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})
plt.show()

In [ ]:
sns.heatmap(corr_matrix, cmap=cmap, vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})
plt.show()

Outlier Detection

In [ ]:
%matplotlib inline
data1.boxplot(column='balancehash')

In [ ]:
data1.boxplot(column='agehash')

In [ ]:
data1.boxplot(column='Tenure')

In [ ]:
data1.boxplot(column='Balance')

In [ ]:
data1.boxplot(column='NumOfProducts')

In [ ]:
data1.boxplot(column='HasCrCard')

In [ ]:
data1.boxplot(column='IsActiveMember')

In [ ]:
data1.boxplot(column='estimatedhash')

In [ ]:
data1.boxplot(column='Gender')

In [ ]:
data1.Age.value_counts()

In [ ]:
data1.CreditScore.value_counts()

In [ ]:
data1

Searching for Bell Graph of Some Attributes

In [ ]:
data1['Gender'].hist(bins=10)

In [ ]:
data1['CreditScore'].hist(bins=10)

In [ ]:
data1['Age'].hist(bins=10)

In [ ]:
data1['Tenure'].hist(bins=10)

In [ ]:
data1['Balance'].hist(bins=10)

In [ ]:
data1['NumOfProducts'].hist(bins=10)

In [ ]:
data1['HasCrCard'].hist(bins=10)

In [ ]:
data1['IsActiveMember'].hist(bins=10)

In [ ]:
data1['EstimatedSalary'].hist(bins=10)

Searching for histograms Graphs for some values

In [ ]:
import seaborn as sns
#CreditScore	Gender	Tenure	NumOfProducts	HasCrCard	IsActiveMember	balancehash	estimatedhash	agehash
sns.displot(data1['CreditScore'])

In [ ]:
sns.displot(data1['Gender'])

In [ ]:
sns.displot(data1['Tenure'])

In [ ]:
sns.displot(data1['NumOfProducts'])

In [ ]:
sns.displot(data1['HasCrCard'])

In [ ]:
sns.displot(data1['IsActiveMember'])

In [ ]:
sns.displot(data1['balancehash'])

In [ ]:
sns.displot(data1['estimatedhash'])

In [ ]:
sns.displot(data1['agehash'])

In [ ]:
data1.describe()

In [ ]:
#replacing num products
data1['NumOfProducts'].replace([4],[1],inplace=True)

In [ ]:
data1

Removing Outliers

In [ ]:
data1.boxplot(column='NumOfProducts')

In [ ]:
data1['CreditScore'] = data1['CreditScore'].mask(data1['CreditScore'] < 380, 652)

In [ ]:
data1.boxplot(column='CreditScore')

In [ ]:
data1['agehash'] = data1['agehash'].mask(data1['agehash'] > 62, 37)

In [ ]:
data1.boxplot(column='agehash')

In [ ]:
exited=data1['Exited']
mean_exited=data1['Exited'].mean()
age=data1['Age']
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns
plt.plot(age,exited,'o')
plt.ylabel('Exited')
plt.xlabel('Age')
plt.axhline(mean_exited,color='r',linestyle='-')
sns.regplot(x='Age',y='Exited',data=data1)

In [ ]:
age=data1['Balance']
plt.plot(age,exited,'o')
plt.ylabel('Exited')
plt.xlabel('Balance')
plt.axhline(mean_exited,color='r',linestyle='-')
sns.regplot(x='Balance',y='Exited',data=data1)

In [ ]:
gen=data1['Gender']
plt.plot(gen,exited,'o')
plt.ylabel('Exited')
plt.xlabel('Gender')
plt.axhline(mean_exited,color='r',linestyle='-')
sns.regplot(x='Gender',y='Exited',data=data1)

In [ ]:
data1=data1.drop(['Exited'], axis=1)

data1=data1.drop(['Age'], axis=1)

data1=data1.drop(['Balance'], axis=1)

In [ ]:
data1

In [ ]:
data1=data1.drop(['EstimatedSalary'], axis=1)

In [ ]:
data1

Train and Split

In [ ]:
from sklearn import preprocessing
minmax =preprocessing.MinMaxScaler(feature_range=(0,1))
z = minmax.fit(data1).transform(data1)
df2 = pd.DataFrame(z)
df2

In [ ]:
data1

In [ ]:
df2 = df2.rename(columns={0:'CreditScore' , 1:'Gender', 2:'Tenure', 3:'NumOfProducts', 4:'HasCrCard', 5:'IsActiveMember', 6:'balancehash', 7:'estimatedhash', 8:'agehash',9:'exihash'})

In [ ]:
df2

In [ ]:
train=df2.groupby('exihash', group_keys=False).apply(lambda x: x.sample(frac=0.8))
test=df2[~df2.isin(train)].dropna()

In [ ]:
y_train= train[['exihash']]
y_test= test[['exihash']]
x_train=train[['CreditScore','Gender','Tenure','NumOfProducts','HasCrCard','IsActiveMember','balancehash','estimatedhash','agehash']]
x_test=test[['CreditScore','Gender','Tenure','NumOfProducts','HasCrCard','IsActiveMember','balancehash','estimatedhash','agehash']]

In [ ]:
y_train['exihash'].value_counts()


In [ ]:
y_test['exihash'].value_counts()


In [ ]:
import pandas as pd
import hashlib
import random
import string
d1 = data1[['CreditScore','Gender','Tenure']].dropna()
display(d1.head())

In [ ]:
d2 = d1.copy()


In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
x_train.head()

In [ ]:
y_train=y_train.astype('int')

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
y_train.head()

In [ ]:
y_test=y_test.astype('int')

In [ ]:
y_test.head()

KNN Algorithm

Fitting classifer to the training set

In [ ]:
from sklearn import neighbors

In [ ]:
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train.values.ravel())

predict on test data

In [ ]:
x_test.head()

In [ ]:
y_pred=clf.predict(x_test)

In [ ]:
y_pred

In [ ]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix

In [ ]:
print("\n accuracy score:%f "%(accuracy_score(y_test,y_pred)*100))
print("\n recall score:%f"%(recall_score(y_test,y_pred)*100))
print("\n roc score :%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))
accuracy_knn = accuracy_score(y_test,y_pred)*100

In [ ]:
from sklearn.metrics import classification_report
knn_report = classification_report(y_test, y_pred)
print('Classification Report:\n', knn_report)

In [ ]:
probas=clf.predict_proba(x_test)

In [ ]:
probas

In [ ]:
import matplotlib.pyplot as plt
plt.figure(dpi=150)
plt.hist(probas,bins=20)
plt.title('Classification Probabilities')
plt.xlabel('Probability')
plt.ylabel('# of instances')
plt.xlim([0.5,1.0])
plt.legend(y_test)
plt.show()

In [ ]:
x_train_std=minmax.fit_transform(x_train)
x_test_std=minmax.transform(x_test)

In [ ]:
import numpy
from sklearn.model_selection import cross_val_score,cross_val_predict
clf_acc=cross_val_score(clf,x_train_std,y_train,cv=3,scoring="accuracy",n_jobs=-1)
clf_proba=cross_val_predict(clf,x_train_std,numpy.ravel(y_train,order = 'C'),cv=3,method='predict_proba')
clf_score=clf_proba[:,1]
clf_score

In [ ]:
clf_acc

Logistic Regression Model

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train.values.ravel())
lr.acc=cross_val_score(lr,x_train_std,numpy.ravel(y_train,order = 'C'),cv=3,scoring='accuracy',n_jobs=-1)
lr_proba=cross_val_predict(lr,x_train_std,numpy.ravel(y_train,order = 'C'),cv=3,method='predict_proba')

In [ ]:
lr_scores=lr_proba[:,1]

In [ ]:
lr_scores

In [ ]:
lr.acc

In [ ]:
y_pred=lr.predict(x_test)

In [ ]:
print("accuracy:%f"%(accuracy_score(y_test,y_pred)*100))
print("\n recall score:%f"%(recall_score(y_test,y_pred)*100))
print("\n roc score :%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))
accuracy_logreg = accuracy_score(y_test,y_pred)*100

In [ ]:
from sklearn.metrics import classification_report
lr_report = classification_report(y_test, y_pred)
print('Classification Report:\n', lr_report)

Support Vector Machine Classifier

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

parameters = {'kernel':('linear', 'poly', 'rbf', 'sigmoid'), 'C':[1, 10]}
svc = SVC()
clf = GridSearchCV(svc, parameters, verbose=1)
clf.fit(x_train, numpy.ravel(y_train,order = 'C'))



In [ ]:
print (clf.best_params_)

In [ ]:
from sklearn.svm import SVC
svc=SVC(**clf.best_params_, probability=True)
svc_classifier=svc.fit(x_train,numpy.ravel(y_train,order = 'C'))

In [103]:
svc_acc=cross_val_score(svc_classifier,x_train_std,y_train,cv=3,scoring="accuracy",n_jobs=-1)

In [104]:
svc_acc

array([0.84326959, 0.84626922, 0.84471118])

In [105]:
svc_proba=cross_val_predict(svc_classifier,x_train_std,numpy.ravel(y_train,order = 'C'),cv=3,method='predict_proba')
svc_scores=svc_proba[:,1]

In [ ]:
svc_scores

array([0.21424011, 0.33670739, 0.14372448, ..., 0.81263498, 0.87965379,
       0.10705212])

predict on test data

In [ ]:
y_pred=svc.predict(x_test)

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix

In [ ]:
print("accuracy:%f"%(accuracy_score(y_test,y_pred)*100))
print("\n recall score:%f"%(recall_score(y_test,y_pred)*100))
print("\n roc score :%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))
accuracy_svc = accuracy_score(y_test,y_pred)*100

accuracy:85.050000

 recall score:35.135135

 roc score :66.469011
[[1558   35]
 [ 264  143]]


In [ ]:
confusion_matrix(y_test,y_pred)

array([[1558,   35],
       [ 264,  143]])

In [ ]:
from sklearn.metrics import classification_report
svc_report = classification_report(y_test, y_pred)
print('Classification Report:\n', svc_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.98      0.91      1593
           1       0.80      0.35      0.49       407

    accuracy                           0.85      2000
   macro avg       0.83      0.66      0.70      2000
weighted avg       0.84      0.85      0.83      2000



Decision Tree Classifier

In [ ]:
param_grid = {
    'max_features': ['sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy', 'log_loss'],
    'splitter'  :['best', 'random']
}


In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc_clf=DecisionTreeClassifier()

CV_dtc_clf=GridSearchCV(estimator=DecisionTreeClassifier(), param_grid=param_grid, cv= 3, verbose=1)

CV_dtc_clf.fit(x_train,y_train)

Fitting 3 folds for each of 60 candidates, totalling 180 fits


GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [4, 5, 6, 7, 8],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=1)

In [ ]:
CV_dtc_clf.best_params_

{'criterion': 'gini',
 'max_depth': 6,
 'max_features': 'log2',
 'splitter': 'best'}

In [ ]:
dtc_clf=DecisionTreeClassifier(criterion= 'log_loss',
                               max_depth=6,
                               max_features= 'sqrt',
                               splitter= 'best')


In [ ]:
dtc_clf.fit(x_train,y_train)

DecisionTreeClassifier(criterion='log_loss', max_depth=6, max_features='sqrt')

In [ ]:
dtc_clf_acc=cross_val_score(dtc_clf,x_train_std,y_train,cv=3,scoring="accuracy",n_jobs=-1)
dtc_proba=cross_val_predict(dtc_clf,x_train_std,numpy.ravel(y_train,order = 'C'),cv=3,method='predict_proba')
dtc_clf_scores=dtc_proba[:,1]

In [ ]:
y_pred=dtc_clf.predict(x_test)

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
dtc_clf_acc

array([0.84326959, 0.84289464, 0.83045761])

In [ ]:
print("accuracy:%f"%(accuracy_score(y_test,y_pred)*100))
print("\n recall score:%f"%(recall_score(y_test,y_pred)*100))
print("\n roc score :%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))
accuracy_dct = accuracy_score(y_test,y_pred)*100

accuracy:84.700000

 recall score:39.557740

 roc score :67.895631
[[1533   60]
 [ 246  161]]


In [ ]:
confusion_matrix(y_test,y_pred)

array([[1533,   60],
       [ 246,  161]])

In [ ]:
from sklearn.metrics import classification_report
dtc_report = classification_report(y_test, y_pred)
print('Classification Report:\n', dtc_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.96      0.91      1593
           1       0.73      0.40      0.51       407

    accuracy                           0.85      2000
   macro avg       0.80      0.68      0.71      2000
weighted avg       0.83      0.85      0.83      2000



Gradient Boosting Classifier

In [ ]:
param_grid = {
    'loss': ['log_loss', 'exponential'],
    'n_estimators' : [50,60,70,80,90,100,110],
    'criterion' :['friedman_mse', 'squared_error'],
    'max_depth'  :[3,4,5,6]
}



In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

CV_gb_clf=GridSearchCV(estimator=GradientBoostingClassifier(), param_grid=param_grid, cv= 3, verbose=2)

CV_gb_clf.fit(x_train,numpy.ravel(y_train))



Fitting 3 folds for each of 112 candidates, totalling 336 fits
[CV] END criterion=friedman_mse, loss=log_loss, max_depth=3, n_estimators=50; total time=   0.4s
[CV] END criterion=friedman_mse, loss=log_loss, max_depth=3, n_estimators=50; total time=   0.3s
[CV] END criterion=friedman_mse, loss=log_loss, max_depth=3, n_estimators=50; total time=   0.3s
[CV] END criterion=friedman_mse, loss=log_loss, max_depth=3, n_estimators=60; total time=   0.4s
[CV] END criterion=friedman_mse, loss=log_loss, max_depth=3, n_estimators=60; total time=   0.4s
[CV] END criterion=friedman_mse, loss=log_loss, max_depth=3, n_estimators=60; total time=   0.5s
[CV] END criterion=friedman_mse, loss=log_loss, max_depth=3, n_estimators=70; total time=   0.7s
[CV] END criterion=friedman_mse, loss=log_loss, max_depth=3, n_estimators=70; total time=   0.7s
[CV] END criterion=friedman_mse, loss=log_loss, max_depth=3, n_estimators=70; total time=   0.7s
[CV] END criterion=friedman_mse, loss=log_loss, max_depth=3, n_e

GridSearchCV(cv=3, estimator=GradientBoostingClassifier(),
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'loss': ['log_loss', 'exponential'],
                         'max_depth': [3, 4, 5, 6],
                         'n_estimators': [50, 60, 70, 80, 90, 100, 110]},
             verbose=2)

In [ ]:
CV_gb_clf.best_params_

{'criterion': 'friedman_mse',
 'loss': 'exponential',
 'max_depth': 3,
 'n_estimators': 80}

In [ ]:
gb = GradientBoostingClassifier(**CV_gb_clf.best_params_)

gb_clf = gb.fit(x_train,numpy.ravel(y_train))


In [ ]:
y_pred = gb_clf.predict(x_test)

In [ ]:
y_test.values

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [ ]:
print("accuracy:%f"%(accuracy_score(y_test,y_pred)*100))
print("\n recall score:%f"%(recall_score(y_test,y_pred)*100))
print("\n roc score :%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))
accuracy_gb = accuracy_score(y_test,y_pred)*100

accuracy:84.800000

 recall score:38.574939

 roc score :67.592554
[[1539   54]
 [ 250  157]]


In [ ]:
confusion_matrix(y_test,y_pred)

array([[1539,   54],
       [ 250,  157]])

In [ ]:
from sklearn.metrics import classification_report
gb_report = classification_report(y_test, y_pred)
print('Classification Report:\n', gb_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.97      0.91      1593
           1       0.74      0.39      0.51       407

    accuracy                           0.85      2000
   macro avg       0.80      0.68      0.71      2000
weighted avg       0.84      0.85      0.83      2000



XGBoost

In [ ]:
param_grid = {
    'use_label_encoder': ['False'],
    'eval_metric' : ['rmse', 'mae', 'logloss', 'error'],
    'eta' :[0.01, 0.05, 0.1, 0.15],
    'max_depth'  :[4,5,6,7],
    'tree_method' :['auto', 'exact', 'approx', 'hist']
}



In [ ]:
from xgboost import XGBClassifier

CV_xgb=GridSearchCV(estimator=XGBClassifier(), param_grid=param_grid, cv= 3, verbose=2)

CV_xgb.fit(x_train,numpy.ravel(y_train))

Fitting 3 folds for each of 256 candidates, totalling 768 fits
[CV] END eta=0.01, eval_metric=rmse, max_depth=4, tree_method=auto, use_label_encoder=False; total time=   0.1s
[CV] END eta=0.01, eval_metric=rmse, max_depth=4, tree_method=auto, use_label_encoder=False; total time=   0.1s
[CV] END eta=0.01, eval_metric=rmse, max_depth=4, tree_method=auto, use_label_encoder=False; total time=   0.1s
[CV] END eta=0.01, eval_metric=rmse, max_depth=4, tree_method=exact, use_label_encoder=False; total time=   0.3s
[CV] END eta=0.01, eval_metric=rmse, max_depth=4, tree_method=exact, use_label_encoder=False; total time=   0.3s
[CV] END eta=0.01, eval_metric=rmse, max_depth=4, tree_method=exact, use_label_encoder=False; total time=   0.3s
[CV] END eta=0.01, eval_metric=rmse, max_depth=4, tree_method=approx, use_label_encoder=False; total time=   0.4s
[CV] END eta=0.01, eval_metric=rmse, max_depth=4, tree_method=approx, use_label_encoder=False; total time=   0.4s
[CV] END eta=0.01, eval_metric=rms

GridSearchCV(cv=3,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None,...
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None,
                                     random_state=None, ...),
             param_grid={'eta': [0.01, 0.05, 0.1, 0.15],
                         'eval_metric': ['rmse', 'mae', 'logloss', 'error'],
                         'max_depth': [4, 5, 6, 7],
                         'tree_method': ['auto', 'exact', 'approx', 'hist'],
                         'use_label_encoder': ['False']},
             verbose=2)

In [ ]:
CV_xgb.best_params_

{'eta': 0.05,
 'eval_metric': 'rmse',
 'max_depth': 5,
 'tree_method': 'auto',
 'use_label_encoder': 'False'}

In [ ]:
xgb = XGBClassifier(**CV_xgb.best_params_)
xgb.fit(x_train, numpy.ravel(y_train))

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eta=0.05, eval_metric='rmse',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
y_pred = xgb.predict(x_test)

In [ ]:
y_test.values

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [ ]:
print("accuracy:%f"%(accuracy_score(y_test,y_pred)*100))
print("\n recall score:%f"%(recall_score(y_test,y_pred)*100))
print("\n roc score :%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))
accuracy_xgb = accuracy_score(y_test,y_pred)*100

accuracy:84.400000

 recall score:40.294840

 roc score :67.981695
[[1524   69]
 [ 243  164]]


In [ ]:
from sklearn.metrics import classification_report
xgb_report = classification_report(y_test, y_pred)
print('Classification Report:\n', xgb_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.96      0.91      1593
           1       0.70      0.40      0.51       407

    accuracy                           0.84      2000
   macro avg       0.78      0.68      0.71      2000
weighted avg       0.83      0.84      0.83      2000



MLP Classifier

In [ ]:
param_grid = {
    'hidden_layer_sizes': [70,80,90,100],
    'activation' : ['relu','logistic'],
    'solver' :['sgd', 'adam'],
    'learning_rate' :['invscaling', 'adaptive']
}



In [ ]:
from sklearn.neural_network import MLPClassifier

CV_mlp=GridSearchCV(estimator=MLPClassifier(), param_grid=param_grid, cv= 3, verbose=2)

CV_mlp.fit(x_train,numpy.ravel(y_train))

Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=invscaling, solver=sgd; total time=   2.5s
[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=invscaling, solver=sgd; total time=   1.9s
[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=invscaling, solver=sgd; total time=   1.2s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=invscaling, solver=adam; total time=   5.1s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=invscaling, solver=adam; total time=   8.7s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=invscaling, solver=adam; total time=   5.2s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=adaptive, solver=sgd; total time=   8.0s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=adaptive, solver=sgd; total time=   4.9s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=adaptive, solver=sgd; total time=   4.7s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=adaptive, solver=adam; total time=   8.5s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=adaptive, solver=adam; total time=   5.2s
[CV] END activation=relu, hidden_layer_sizes=70, learning_rate=adaptive, solver=adam; total time=   7.2s
[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=invscaling, solver=sgd; total time=   1.6s
[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=invscaling, solver=sgd; total time=   2.4s
[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=invscaling, solver=sgd; total time=   1.6s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=invscaling, solver=adam; total time=   5.4s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=invscaling, solver=adam; total time=   9.0s
[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=invscaling, solver=adam; total time=   4.7s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=adaptive, solver=sgd; total time=   8.1s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=adaptive, solver=sgd; total time=   5.6s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=adaptive, solver=sgd; total time=   5.2s
[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=adaptive, solver=adam; total time=   8.4s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=adaptive, solver=adam; total time=   5.4s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=80, learning_rate=adaptive, solver=adam; total time=   8.6s
[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=invscaling, solver=sgd; total time=   1.0s
[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=invscaling, solver=sgd; total time=   1.3s
[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=invscaling, solver=sgd; total time=   1.6s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=invscaling, solver=adam; total time=   6.4s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=invscaling, solver=adam; total time=   8.8s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=invscaling, solver=adam; total time=   5.7s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=adaptive, solver=sgd; total time=   8.7s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=adaptive, solver=sgd; total time=   5.4s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=adaptive, solver=sgd; total time=   7.2s
[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=adaptive, solver=adam; total time=   5.6s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=adaptive, solver=adam; total time=   9.1s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=90, learning_rate=adaptive, solver=adam; total time=   5.8s
[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=invscaling, solver=sgd; total time=   2.2s
[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=invscaling, solver=sgd; total time=   2.7s
[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=invscaling, solver=sgd; total time=   0.9s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=invscaling, solver=adam; total time=   8.4s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=invscaling, solver=adam; total time=   6.4s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=invscaling, solver=adam; total time=   9.2s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=adaptive, solver=sgd; total time=   5.8s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=adaptive, solver=sgd; total time=   9.3s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=adaptive, solver=sgd; total time=   5.8s
[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=adaptive, solver=adam; total time=   8.0s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=adaptive, solver=adam; total time=   6.1s


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV] END activation=relu, hidden_layer_sizes=100, learning_rate=adaptive, solver=adam; total time=   9.5s
[CV] END activation=logistic, hidden_layer_sizes=70, learning_rate=invscaling, solver=sgd; total time=   0.5s
[CV] END activation=logistic, hidden_layer_sizes=70, learning_rate=invscaling, solver=sgd; total time=   0.4s
[CV] END activation=logistic, hidden_layer_sizes=70, learning_rate=invscaling, solver=sgd; total time=   0.5s
[CV] END activation=logistic, hidden_layer_sizes=70, learning_rate=invscaling, solver=adam; total time=   2.8s
[CV] END activation=logistic, hidden_layer_sizes=70, learning_rate=invscaling, solver=adam; total time=   2.6s
[CV] END activation=logistic, hidden_layer_sizes=70, learning_rate=invscaling, solver=adam; total time=   2.6s
[CV] END activation=logistic, hidden_layer_sizes=70, learning_rate=adaptive, solver=sgd; total time=   3.9s
[CV] END activation=logistic, hidden_layer_sizes=70, learning_rate=adaptive, solver=sgd; total time=   3.6s
[CV] END activa

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


GridSearchCV(cv=3, estimator=MLPClassifier(),
             param_grid={'activation': ['relu', 'logistic'],
                         'hidden_layer_sizes': [70, 80, 90, 100],
                         'learning_rate': ['invscaling', 'adaptive'],
                         'solver': ['sgd', 'adam']},
             verbose=2)

In [145]:
CV_mlp.best_params_

{'activation': 'relu',
 'hidden_layer_sizes': 80,
 'learning_rate': 'invscaling',
 'solver': 'adam'}

In [148]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(**CV_mlp.best_params_)

In [149]:
mlp.fit(x_train, numpy.ravel(y_train))

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=80, learning_rate='invscaling')

In [150]:
y_pred=mlp.predict(x_test)

In [151]:
y_test.values

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [152]:
print("accuracy:%f"%(accuracy_score(y_test,y_pred)*100))
print("\n recall score:%f"%(recall_score(y_test,y_pred)*100))
print("\n roc score :%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))
accuracy_mlp = accuracy_score(y_test,y_pred)*100

accuracy:84.250000

 recall score:41.523342

 roc score :68.344847
[[1516   77]
 [ 238  169]]


In [153]:
confusion_matrix(y_test,y_pred)

array([[1516,   77],
       [ 238,  169]])

In [154]:
from sklearn.metrics import classification_report
mlp_report = classification_report(y_test, y_pred)
print('Classification Report:\n', mlp_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.95      0.91      1593
           1       0.69      0.42      0.52       407

    accuracy                           0.84      2000
   macro avg       0.78      0.68      0.71      2000
weighted avg       0.83      0.84      0.83      2000



Random Forest Classifier

In [156]:
param_grid = {
    'n_estimators': [70,80,90,100,110],
    'criterion' : ['gini', 'entropy', 'log_loss'],
    'max_depth' :[4,5,6,7,8],
    'max_features' :['sqrt', 'log2', None]
}



In [157]:
from sklearn.ensemble import RandomForestClassifier

CV_rfc=GridSearchCV(estimator=RandomForestClassifier(), param_grid=param_grid, cv= 3, verbose=2)

CV_rfc.fit(x_train,numpy.ravel(y_train))


Fitting 3 folds for each of 225 candidates, totalling 675 fits
[CV] END criterion=gini, max_depth=4, max_features=sqrt, n_estimators=70; total time=   0.8s
[CV] END criterion=gini, max_depth=4, max_features=sqrt, n_estimators=70; total time=   0.9s
[CV] END criterion=gini, max_depth=4, max_features=sqrt, n_estimators=70; total time=   1.2s
[CV] END criterion=gini, max_depth=4, max_features=sqrt, n_estimators=80; total time=   1.0s
[CV] END criterion=gini, max_depth=4, max_features=sqrt, n_estimators=80; total time=   1.1s
[CV] END criterion=gini, max_depth=4, max_features=sqrt, n_estimators=80; total time=   0.6s
[CV] END criterion=gini, max_depth=4, max_features=sqrt, n_estimators=90; total time=   0.6s
[CV] END criterion=gini, max_depth=4, max_features=sqrt, n_estimators=90; total time=   0.9s
[CV] END criterion=gini, max_depth=4, max_features=sqrt, n_estimators=90; total time=   0.3s
[CV] END criterion=gini, max_depth=4, max_features=sqrt, n_estimators=100; total time=   0.4s
[CV] E

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [4, 5, 6, 7, 8],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [70, 80, 90, 100, 110]},
             verbose=2)

In [159]:
CV_rfc.best_params_

{'criterion': 'log_loss',
 'max_depth': 7,
 'max_features': 'log2',
 'n_estimators': 100}

In [160]:
rmf=RandomForestClassifier(**CV_rfc.best_params_)
rmf_clf=rmf.fit(x_train,numpy.ravel(y_train))

In [161]:
y_pred=rmf_clf.predict(x_test)

In [162]:
y_test.values

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [163]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix

In [164]:
print("accuracy:%f"%(accuracy_score(y_test,y_pred)*100))
print("\n recall score:%f"%(recall_score(y_test,y_pred)*100))
print("\n roc score :%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))
accuracy_rf = accuracy_score(y_test,y_pred)*100

accuracy:84.850000

 recall score:36.609337

 roc score :66.892239
[[1548   45]
 [ 258  149]]


In [165]:
confusion_matrix(y_test,y_pred)

array([[1548,   45],
       [ 258,  149]])

In [166]:
from sklearn.metrics import classification_report
rf_report = classification_report(y_test, y_pred)
print('Classification Report:\n', rf_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.97      0.91      1593
           1       0.77      0.37      0.50       407

    accuracy                           0.85      2000
   macro avg       0.81      0.67      0.70      2000
weighted avg       0.84      0.85      0.83      2000



In [167]:
!pip install tabulate

In [168]:
accuracy_list=[]
accuracy_list.append(accuracy_knn)
accuracy_list.append(accuracy_logreg)
accuracy_list.append(accuracy_svc)
accuracy_list.append(accuracy_dct)
accuracy_list.append(accuracy_gb)
accuracy_list.append(accuracy_xgb)
accuracy_list.append(accuracy_rf)
accuracy_list.append(accuracy_mlp)
accuracy_list




[83.7, 82.45, 85.05, 84.7, 84.8, 84.39999999999999, 84.85000000000001, 84.25]

In [169]:
accuracy_list.sort()
accuracy_list

[82.45, 83.7, 84.25, 84.39999999999999, 84.7, 84.8, 84.85000000000001, 85.05]

In [171]:
highest_accuracy = accuracy_list[-1]
highest_accuracy

85.05

In [172]:
# import pickle
# pickle.dump(x,open('dataset.pkl','wb'))
# pickle.dump(y,open('dataset1.pkl','wb'))
# pickle.dump(data1,open('dataset2.pkl','wb'))

In [173]:
# Predict churn on the test dataset
y_pred_prob = gb_clf.predict_proba(x_test)[:, 1]  # Get the probability of the positive class

In [174]:
# Convert probabilities to a DataFrame for better analysis
probabilities_df = pd.DataFrame(y_pred_prob, columns=['Churn_Probability'])

# Add actual churn labels and predicted labels for comparison
probabilities_df['Actual_Churn'] = y_test.values
probabilities_df['Predicted_Churn'] = y_pred

# Display the head of the DataFrame
print(probabilities_df.head())

# Calculate the average churn probability
average_churn_probability = probabilities_df['Churn_Probability'].mean()
print('Average churn probability: {:.4f}'.format(average_churn_probability))

   Churn_Probability  Actual_Churn  Predicted_Churn
0           0.064118             0                0
1           0.285492             0                0
2           0.148881             1                0
3           0.132904             0                0
4           0.082710             0                0
Average churn probability: 0.2002
